# Port to run the ServerSelectorX API on.
# ServerSelectorX-Connector connects to this port to send server information.
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Installing-SSX-Connector
port: 9782

# If you are using shared hosting, you may need to set this to "0.0.0.0"
# Using shared hosting is not recommended since it is usually not secure!
# If set to "127.0.0.1", the ServerSelectorX API will not be accessible externally.
host: "127.0.0.1"

# IPv6 should be supported, but I can't test it since of course my ISP hasn't rolled
# that out yet. If it works for you please let me know!


# -------------------- Advanced -------------------- #

# The number of milliseconds without a ping until ServerSelectorX
# will consider a server as offline.
server-offline-timeout: 6000

# Enable this to allow config sync to retrieve files from this API.
# WARNING: This will expose ALL files on your system that the user
# running the server process has access to. Only enable this if
# your API is not open to the internet!!
files-api: false
