# IMPORTANT

# Read into what this is about before touching these options
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Config-sync-v2
#
# If configured incorrectly, this WILL DELETE YOUR CONFIG FILES.
#
# Again, this is NOT related to SSX-Connector. Do NOT configure this
# unless you are very sure you know what this does. I hate having
# to put this giant comment here, but unfortunately too many people
# keep turning this on and deleting their config files.

enabled: false

# Server to retrieve configuration files from
address: '123.45.67.89:9782'

files:
 - config/effects.yml
 - command/servers.yml

directories:
 - menu # Sync all files in the menu directory

# Any files to exclude from the directories above
exclude: []



# -------------------- Advanced -------------------- #
 
# When set to true, delete ALL files in the menu, item and command directories.
# Files in the config directory will not be deleted (api.yml, effects.yml, etc.)
# Useful if you want files deleted on one server to be automatically deleted on other servers as well.
# Do not enable if you have config files on this server that you don't have on other servers.
delete: false

# Sync interval in minutes. The server needs to be restarted for this option to take effect.
# When set to 30, the config will be synced at startup then every 30 minutes.
# Use /ssx sync to force sync (/ssx sync will work even if sync is disabled)
interval: 30

# Run commands when config sync is complete, for example to
# reload other plugins if you sync other plugin config files.
after-sync-commands: []
